apiVersion: monitoring.ck.io/v1
kind: PodWatcher
metadata:
  labels:
    app.kubernetes.io/name: podwatcher-operator
    app.kubernetes.io/managed-by: kustomize
  name: podwatcher-sample
spec:
  # TODO(user): Add fields here
